export const electricity = [
    {
        name: "Agva superspot",
        surcharge: -2.17,
        price: "6,659",
        conditions: "Terms are guaranteed in 12 months",
        fee: "No breaking fee",
        spot: "Timespot",
    },
    {
        name: "Agva superspot",
        surcharge: -2.17,
        price: "6,659",
        conditions: "Terms are guaranteed in 12 months",
        fee: "No breaking fee",
        spot: "Timespot",
    },
    {
        name: "Agva superspot",
        surcharge: -2.17,
        price: "6,659",
        conditions: "Terms are guaranteed in 12 months",
        fee: "No breaking fee",
        spot: "Timespot",
    },
    {
        name: "Agva superspot",
        surcharge: -2.17,
        price: "6,659",
        conditions: "Terms are guaranteed in 12 months",
        fee: "No breaking fee",
        spot: "Timespot",
    },
    {
        name: "Agva superspot",
        surcharge: -2.17,
        price: "6,659",
        conditions: "Terms are guaranteed in 12 months",
        fee: "No breaking fee",
        spot: "Timespot",
    },
    {
        name: "Agva superspot",
        surcharge: -2.17,
        price: "6,659",
        conditions: "Terms are guaranteed in 12 months",
        fee: "No breaking fee",
        spot: "Timespot",
    },
]